//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.1433
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPodME.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iPodME.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ffmpeg {
            get {
                object obj = ResourceManager.GetObject("ffmpeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta content=&quot;text/html; charset=ISO-8859-1&quot; http-equiv=&quot;content-type&quot;&gt;
        ///  &lt;title&gt;iPodME Help&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;iPodME Help&lt;/h1&gt;
        ///Quick jump to :&lt;br&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;&lt;a href=&quot;#About_the_profiles&quot;&gt;About the profiles&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;#Using_subtitles&quot;&gt;Using subtitles&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;#Advanced_options&quot;&gt;Advanced options&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;&lt;a href=&quot;#Troubleshooting&quot;&gt;Troubleshooting&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string iPodME_Help {
            get {
                return ResourceManager.GetString("iPodME_Help", resourceCulture);
            }
        }
        
        internal static byte[] js32 {
            get {
                object obj = ResourceManager.GetObject("js32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mp4box {
            get {
                object obj = ResourceManager.GetObject("mp4box", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
